### ISSUE TITLE
Arch Linux NVIM Trace on startup

### ISSUE THREAD

**Issue by MBuchaus** [cwoac/nvim#40]
"_nvim" [New File]
Error detected while processing function NVIM_init[12]..<SNR>39_DefPython:
line    2:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/marty/.vim/bundle/nvim/python/nvim.py", line 3, in <module>
    import xapian
  File "/usr/lib/python2.7/site-packages/xapian/__init__.py", line 43, in <module>
    _xapian = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/xapian/__init__.py", line 39, in swig_import_helper
    _mod = imp.load_module('_xapian', fp, pathname, description)
ImportError: /usr/lib/python2.7/site-packages/xapian/_xapian.so: undefined symbol: PyExc_ValueError

I've installed the xapian for python2.7 and well above we have this un defined symbol
python2-xapian 1.2.22
vim 7.4

**Comment by Granitas** [comment]
I have the same issue. Seems like there's something wrong with `_xapian.so` library. AFAIK the one on pacman is the latest version 1.2.22. It fails on xapion import and I can import `xapion` in python decently.

It could also be caused that default python for arch is python3 and there some confusion going on in `nvim`'s internals.

**Comment by soleblaze** [comment]
Arch recently switched vim to support [python dynamically](https://bugs.archlinux.org/task/47500). This issue is like the one reported [here](https://github.com/cwoac/nvim/issues/19). From what I understand, Xapian considers it an [issue](https://trac.xapian.org/ticket/623) with how vim is handling things and vim considers it an issue with Xapian.

**Comment by cwoac** [comment]
Now working on arch linux.
